### ISSUE TITLE
Killing the Android Glyph cache

### ISSUE THREAD

**Issue by slightfoot** [androidessence/PinchZoomTextView#1]
You might want to think about setting the `LINEAR_TEXT_FLAG` flag when the `ACTION_DOWN` even happens and removing it on the `ACTION_UP`/`ACTION_CANCEL` event. You can use `TextView.setPaintFlags` to achieve this.

https://developer.android.com/reference/android/graphics/Paint.html#LINEAR_TEXT_FLAG

**Comment by AdamMc331** [comment]
Can you explain the purpose of setting this flag?

**Comment by slightfoot** [comment]
I think the documentation says it all. Using this flag mean the glyph cache doesn't store font glyph's for all the sizes in-between whilst resizing. This is good as rendering those only happens when resizing and not after/before.

**Comment by AdamMc331** [comment]
Gotcha. Definitely something we can do, thanks!

**Comment by AdamMc331** [comment]
Wow, this does make it a lot more clear. Thank you so much for the suggestion.

**Comment by slightfoot** [comment]
Hope you don't mind but I have some code suggestions on that commit. Will comment on the commit itself.

**Comment by AdamMc331** [comment]
That's fine. I was going to ask for your blessing on the PR before I merged it, but this is even better.

**Comment by AdamMc331** [comment]
@slightfoot Thank you for that, that's really important to avoid meddling with the user's current flags. Can't believe I overlooked that.

**Comment by slightfoot** [comment]
I have another suggestion just looking at the code. But unrelated to this issue. I'll see if I can submit a PR later. Your little library covers a topic I've done in depth before. So I have a lot of suggestions. ;)

**Comment by AdamMc331** [comment]
For sure. Thanks!
